<?php

namespace app\controllers;

use app\components\gui\Breadcrumb;
use app\components\gui\ActionItem;
use app\models\data\ExportForm;
use yii\helpers\Json;

/**
 * Class DataController
 *
 * Imports and exports dream data.
 *
 * @package app\controllers
 */
class DataController extends BaseController
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [];
	}

	public function beforeAction($action)
	{
		$this->addBreadcrumb(new Breadcrumb('Data', '/data'));
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function actionExport()
	{
		$this->getView()->title = 'Export Dreams';
		$this->addBreadcrumb(new Breadcrumb('Export', '', true));

		$exportForm = new ExportForm();

		$request = \Yii::$app->request;
		if($request->getIsPost())
		{
			$exportForm->load($request->post());
			$dreams = $exportForm->getDreams();

			$file = tmpfile();
			fwrite($file, Json::encode($dreams, JSON_PRETTY_PRINT));
			return \Yii::$app->response->sendStreamAsFile($file, 'dream-export-' . date('Y-m-d') . '.json');
		}

		return $this->render('export', [
			'exportForm' => $exportForm
		]);
	}

	public function actionImport()
	{
		$this->getView()->title = 'Import Dreams';
		$this->addBreadcrumb(new Breadcrumb('Import', '', true));

		return $this->render('import');
	}
}