<?php

namespace app\controllers;

use app\components\gui\Breadcrumb;
use app\components\gui\ActionItem;
use app\models\data\ExportForm;
use app\models\dj\Dream;
use yii\helpers\Json;

/**
 * Class DataController
 *
 * Imports and exports dream data.
 *
 * @package app\controllers
 */
class DataController extends BaseController
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [];
	}

	public function beforeAction($action)
	{
		$this->addBreadcrumb(new Breadcrumb('Data', '/data'));
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function actionExport()
	{
		$this->getView()->title = 'Export Dreams';
		$this->addBreadcrumb(new Breadcrumb('Export', '', true));

		$exportForm = new ExportForm();

		$request = \Yii::$app->request;
		if($request->getIsPost())
		{
			$exportForm->load($request->post());

			if($exportForm->format == 'json')
			{
				//Send JSON data
				$dreams = $exportForm->getDreamData();
				$file = tmpfile();
				fwrite($file, Json::encode($dreams, JSON_PRETTY_PRINT));
				return \Yii::$app->response->sendStreamAsFile($file, 'dream-export-' . date('Y-m-d') . '.json');
			}
			else
			{
				//Render HTML data

				//Group dreams by date
				$dateToDreams = [];
				$dreamCount = 0;

				foreach($exportForm->getDreams() as $dream)
				{
					$dreamCount++;
					$dreamDate = $dream->getFormattedDate();
					if(!isset($dateToDreams[$dreamDate]))
					{
						$dateToDreams[$dreamDate] = [];
					}
					$dateToDreams[$dreamDate][] = $dream;
				}

				$data = [];
				$data['dateToDreams'] = $dateToDreams;
				$data['dreamCount'] = $dreamCount;
				$data['userName'] = 'Sheldon Juncker';
				$data['currentTime'] = date('l, F dS Y');
				return $this->renderPartial('export-html', $data);
			}
		}

		return $this->render('export', [
			'exportForm' => $exportForm
		]);
	}

	public function actionImport()
	{
		$this->getView()->title = 'Import Dreams';
		$this->addBreadcrumb(new Breadcrumb('Import', '', true));

		return $this->render('import');
	}
}